### PR TITLE
[semver:minor] fix: remove GPG verification

### PR DESCRIPTION
**Pull request by wbeuil**

### CODE REVIEW

**Review by eliecharra — APPROVED** [review]
That sounds great, but dctlenv version should be bumped to include https://github.com/wbeuil/dctlenv/issues/22

**Comment by wbeuil** [comment]
@eliecharra yep will bump it probably tomorrow once I finish my PR on dctlenv.

I also added the [Publish version tag to GitHub](https://circleci.com/docs/2.0/creating-orbs/#publish-version-tag-to-github) feature.

My IDE also format the yml file on save.

**Comment by eliecharra** [comment]
> I also added the Publish version tag to GitHub feature.

Thanks this is great, I really prefer this way for release publishing. Can you update the readme ?

**Comment by wbeuil** [comment]
Sorry to say it won't change the way of publishing. It's just a feature to push a tag to Github at the end of the circle ci publishing pipeline ...

**Comment by eliecharra** [comment]
> Sorry to say it won't change the way of publishing. It's just a feature to push a tag to Github at the end of the circle ci publishing pipeline ...

Oh ok sorry I misunderstood that, no worries

**Pull request merged**
